Create flutter-ci.yml
IEEE-VIT/hacktoberfest-flutter pull request #12
Opened 2020-10-01 22:47 UTC by Mastersam07

# Story Title

[Add GitHub action to format code upon merge with master](https://github.com/IEEE-VIT/hacktoberfest-flutter/issues/11)

## Changes made

-   added flutter-ci.yaml
-   run flutter analyze . and format code on pull request closed and merged

## How does the solution address the problem

This PR will check for closed pull requests that were merged to master, run flutter linting analysis and format codebase.

## Linked issues

Resolves #11

2020-10-02 21:40 UTC, DarthBenro008 requested changes
@Mastersam07 so there was a internal discussion and its been final that the CI should check lint on every PR and Push to master branch, hence make the changes accordingly, everything else seems good. Nice Work! :)

2020-10-02 21:40 UTC, DarthBenro008 commented on .github/workflows/flutter-ci.yml
> +
kindly change this to pull request of any kind to master.

2020-10-02 21:40 UTC, DarthBenro008 commented on .github/workflows/flutter-ci.yml
> +    if: github.event.pull_request.merged == true
please remove this check

2020-10-03 00:31 UTC, Mastersam07 commented
@DarthBenro008 how about now?

2020-10-03 08:26 UTC, DarthBenro008 approved these changes
LGTM!

2020-10-04 12:54 UTC, merged